### ISSUE TITLE
SIGSEGV in NetworkDiscover::getHostAddresses (Fedora 38)

### ISSUE THREAD

**Issue by cutephoton** [aurgatech/linux-binaries#2]
On Fedora 38:

```
Thread 5 "AURGAViewer" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe9ffe6c0 (LWP 2680413)]
0x0000000000517ccf in NetworkDiscover::getHostAddresses() ()
```

```
#0  0x0000000000517ccf in NetworkDiscover::getHostAddresses() ()
#1  0x00000000005114ff in NetworkDiscover::scanRunloop() ()
#2  0x00000000005107dd in scanCallback(void*) ()
#3  0x00007ffff7aac947 in start_thread () from /lib64/libc.so.6
#4  0x00007ffff7b32860 in clone3 () from /lib64/libc.so.6
```

**Comment by portavales** [comment]
How did you fix this ?
I am having the same problem and AURGAViewer just crashes and I cant use it anymore.
